name: Ember rAF Scheduler CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Volta
        uses: volta-cli/action@v4

      - name: Node Modules Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ci-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test:ember
        env:
          CI: true

  test-ember-try:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ember-version:
          [
            ember-lts-3.12,
            ember-lts-3.16,
            ember-lts-3.28,
            ember-lts-4.4,
            ember-lts-4.12,
            ember-5.2,
            ember-release,
            ember-beta,
            ember-canary,
            embroider-safe,
            # embroider-optimized
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Volta
        uses: volta-cli/action@v1

      - name: Install
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Run Tests
        run: node_modules/.bin/ember try:one ${{ matrix.ember-version }} --skip-cleanup
